### PR TITLE
Added oplog('open', [fn])

### PR DESCRIPTION
**Pull request by kleysonr**
Reference: https://github.com/cayasso/mongo-oplog/issues/24

### CODE REVIEW

**Comment by kleysonr** [comment]
@cayasso I have no experience with test/mocha to add a properly test case.

But to become mongo-oplog compatible with ES6 Promise, I believe that cb is necessary. See the following example:

```javascript
var uri = ...
var filter = ...

var initOplog = function() 
{
	return new Promise(function(resolve, reject) 
	{
	  	let oplog = MongoOplog(uri, filter).tail();

	  	oplog.on('insert', function(doc) {
	  		console.log(doc);
	  	});

	  	oplog.on('open', function () 
	  	{
	  		resolve();
	  	});

	  	oplog.on('error', function (err) 
	  	{
	  		reject(err);
	  	});
	});
}

initOplog(uri, filter).then(function() {
	console.log('Oplog started.');
}).catch(function(err) {
	console.log(err);
})
```

Then, I need some way to return a resolve() in case of success, or a reject() in case of error.

So, if there is another way to do it, please let me know.

Best Regards.

**Comment by cayasso** [comment]
@kleysonr one important thing to note here is that the mongodb connection is a lazy connection, meaning that it will only connect when you call the `tail` method, that has been the reason not to add an `open` event now that I remember, so you can hook your Promise to the `tail` method callback. 

Also its not a good idea to hook your Promise to the `error` event, because this will fire at any time with any error including cursor stream errors.

And lastly I think you are confused with the EventEmitter concept in node:
you DONT need a callback function when you trigger an event unless you want a response from the event: 

```js
this.on('open', function() {
 console.log('CONNECTED');
});

this.emit('open');
```
or waiting for response:
```js
this.on('open', function(fn) {
 console.log('CONNECTED');
 fn('GOT IT');
});

this.emit('open', function(msg){
console.log(msg); // => GOT IT
});
```

Cheers,

**Comment by cayasso** [comment]
Additional info on Promises, promises should only be resolved (or rejected) once https://promisesaplus.com/#promise_states

Additional info on EventEmitter in NodeJS https://nodejs.org/api/events.html

**Comment by kleysonr** [comment]
@cayasso I'm not an experienced developer in Node.js and probably I'm missing something as you said.

But before I've tried what you suggest, putting the resolve() in the tail method. But I had some problems. First, I had to create some way to control that resolve() would be called just once. Second, all my init process was stopped waiting for the promise. I mean, connecting to mongo-oplog belong to a init process, so I was not able to finish the process before start processing the tail output.

I've changed the mongo-oplog in my server to add the .on('open'), and the behavior is as expected. I don't know if in the future that can bring some headache. And I thought that wouldn't be a problem because Mongoose has a .once('open', [fn])) like I suggested to you.

Cheers.

**Pull request closed without merging**
